version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
       - '6603:3306'
      environment:
        MYSQL_ROOT_PASSWORD: krzyzak!18

   phpmyadmin:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db

   web:
     build: .
     command: sh -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
     volumes:
       - .:/code/
     ports:
       - "8000:8000"
