# Generated by Django 3.0.7 on 2020-07-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mqtt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=50)),
                ('trest2', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Mqtt',
                'verbose_name_plural': 'Mqtt',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
