# Generated by Django 3.1.3 on 2021-05-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rodzaj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank', models.IntegerField(choices=[(1, 'Teroidalny wewnętrzny'), (2, 'Teroidalny zewnętrzny'), (3, 'Teroidalny zewnętrzny pełny'), (4, 'Walcowy')], default=1)),
                ('symbol', models.CharField(max_length=8, unique=True)),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Wysokość')),
                ('capacity', models.IntegerField(verbose_name='Pojemność')),
                ('dimeter', models.IntegerField(verbose_name='Średnica')),
                ('approval', models.CharField(max_length=16, verbose_name='Homologacja')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Waga')),
            ],
            options={
                'verbose_name': 'Rodzaj',
                'verbose_name_plural': 'Rodzaje',
            },
        ),
    ]
